services:
  postgres:
    image: postgres:16
    container_name: opentargets_postgres
    environment:
      POSTGRES_USER: shikhar
      POSTGRES_PASSWORD: opentargets
      POSTGRES_DB: opentargets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: